// frontend/src/components/ui/StatusBadge.tsx
import React from 'react';
import { cn } from '../../lib/cn';

interface StatusBadgeProps {
  status: string | null | undefined;
  className?: string;
}

const STATUS_MAP: Record<string, { label: string; className: string; dotClassName: string }> = {
  running: {
    label: 'Running',
    className: 'border-accent-blue/25 bg-accent-blue/10 text-accent-blue-light',
    dotClassName: 'bg-accent-blue shadow-[0_0_0_4px_rgba(99,102,241,0.14)]',
  },
  completed: {
    label: 'Completed',
    className: 'border-accent-green/25 bg-accent-green/10 text-accent-green',
    dotClassName: 'bg-accent-green shadow-[0_0_0_4px_rgba(34,197,94,0.12)]',
  },
  approved: {
    label: 'Approved',
    className: 'border-accent-green/25 bg-accent-green/10 text-accent-green',
    dotClassName: 'bg-accent-green shadow-[0_0_0_4px_rgba(34,197,94,0.12)]',
  },
  failed: {
    label: 'Failed',
    className: 'border-accent-rose/25 bg-accent-rose/10 text-accent-rose',
    dotClassName: 'bg-accent-rose shadow-[0_0_0_4px_rgba(244,63,94,0.12)]',
  },
  paused: {
    label: 'Needs review',
    className: 'border-accent-amber/25 bg-accent-amber/10 text-accent-amber',
    dotClassName: 'bg-accent-amber shadow-[0_0_0_4px_rgba(245,158,11,0.12)]',
  },
  pending: {
    label: 'Pending',
    className: 'border-white/10 bg-white/5 text-gray-300',
    dotClassName: 'bg-gray-500 shadow-[0_0_0_4px_rgba(107,114,128,0.12)]',
  },
};

const StatusBadge: React.FC<StatusBadgeProps> = ({ status, className }) => {
  const normalizedStatus = (status || 'pending').toLowerCase();
  const style = STATUS_MAP[normalizedStatus] ?? STATUS_MAP.pending;

  return (
    <span
      className={cn(
        'inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em]',
        style.className,
        className,
      )}
    >
      <span className={cn('h-2 w-2 rounded-full', style.dotClassName)} />
      {style.label}
    </span>
  );
};

export default StatusBadge;

// frontend/src/components/app/StatusBadge.vue
<template>
  <Tag :value="label" rounded :class="badgeClass" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Tag from 'primevue/tag';

const props = defineProps<{
  status: string | null | undefined;
}>();

const normalizedStatus = computed(() => (props.status || 'pending').toLowerCase());

const label = computed(() => {
  switch (normalizedStatus.value) {
    case 'running':
      return 'Running';
    case 'completed':
      return 'Completed';
    case 'approved':
      return 'Approved';
    case 'failed':
      return 'Failed';
    case 'paused':
    case 'waiting_for_approval':
      return 'Needs review';
    default:
      return 'Pending';
  }
});

const badgeClass = computed(() => ({
  'surface-status': true,
  'surface-status--running': normalizedStatus.value === 'running',
  'surface-status--completed': normalizedStatus.value === 'completed' || normalizedStatus.value === 'approved',
  'surface-status--failed': normalizedStatus.value === 'failed',
  'surface-status--paused':
    normalizedStatus.value === 'paused' || normalizedStatus.value === 'waiting_for_approval',
  'surface-status--pending':
    !['running', 'completed', 'approved', 'failed', 'paused', 'waiting_for_approval'].includes(normalizedStatus.value),
}));
</script>

<style scoped>
.surface-status {
  font-size: 0.72rem;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  font-weight: 700;
  border: 1px solid transparent;
}

.surface-status--running {
  background: var(--app-accent-soft);
  color: var(--app-accent);
  border-color: rgba(18, 128, 92, 0.18);
}

.surface-status--completed {
  background: rgba(22, 163, 74, 0.12);
  color: #15803d;
  border-color: rgba(22, 163, 74, 0.16);
}

.surface-status--failed {
  background: rgba(220, 38, 38, 0.12);
  color: #dc2626;
  border-color: rgba(220, 38, 38, 0.16);
}

.surface-status--paused {
  background: rgba(217, 119, 6, 0.14);
  color: #b45309;
  border-color: rgba(217, 119, 6, 0.2);
}

.surface-status--pending {
  background: rgba(148, 163, 184, 0.12);
  color: var(--app-text-soft);
  border-color: var(--app-border);
}

:global(html.app-dark) .surface-status--completed {
  color: #86efac;
}

:global(html.app-dark) .surface-status--failed {
  color: #fca5a5;
}

:global(html.app-dark) .surface-status--paused {
  color: #fdba74;
}
</style>
