// frontend/src/pages/OAuthCallbackPage.vue
<template>
  <AuthShell
    eyebrow="Connecting Account"
    title="Completing your sign in"
    description="We are finalizing your session and preparing the workspace."
  >
    <div class="callback-state">
      <ProgressSpinner stroke-width="4" style="width: 3rem; height: 3rem" />
      <div class="flex flex-column gap-2 text-center">
        <div class="text-lg font-semibold">Signing you in</div>
        <p class="m-0 app-subheading">
          Your account has been verified. You will be redirected as soon as your profile is ready.
        </p>
      </div>
      <Message v-if="error" severity="error" class="w-full">
        {{ error }}
      </Message>
    </div>
  </AuthShell>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import Message from 'primevue/message';
import ProgressSpinner from 'primevue/progressspinner';

import AuthShell from '@/components/auth/AuthShell.vue';
import { getErrorMessage } from '@/lib/workflow';
import { useAuthStore } from '@/stores/auth';

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const error = ref('');

onMounted(async () => {
  const accessToken = route.query.access_token;
  const refreshToken = route.query.refresh_token;

  if (typeof accessToken !== 'string' || typeof refreshToken !== 'string') {
    await router.replace('/login');
    return;
  }

  try {
    authStore.setTokens(accessToken, refreshToken);
    await authStore.loadUser();
    await router.replace('/');
  } catch (err) {
    error.value = getErrorMessage(err, 'Unable to complete sign in.');
    window.localStorage.removeItem('access_token');
    window.localStorage.removeItem('refresh_token');
    window.setTimeout(() => {
      router.replace('/login').catch(() => {
        // no-op
      });
    }, 1200);
  }
});
</script>

<style scoped>
.callback-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  padding: 1.25rem 0 0.25rem;
}
</style>

// frontend/src/pages/OAuthCallbackPage.tsx
import React, { useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { LoaderCircle } from 'lucide-react';
import { useAuthStore } from '../stores/authStore';
import AuthLayout from '../components/layout/AuthLayout';

const OAuthCallbackPage: React.FC = () => {
  const [searchParams] = useSearchParams();
  const setTokens = useAuthStore((state) => state.setTokens);
  const loadUser = useAuthStore((state) => state.loadUser);
  const navigate = useNavigate();

  useEffect(() => {
    const accessToken = searchParams.get('access_token');
    const refreshToken = searchParams.get('refresh_token');

    if (accessToken && refreshToken) {
      setTokens(accessToken, refreshToken);
      loadUser().then(() => navigate('/'));
    } else {
      navigate('/login');
    }
  }, [searchParams, setTokens, loadUser, navigate]);

  return (
    <AuthLayout
      eyebrow="Connecting account"
      title="Completing your sign-in"
      description="We are finalizing your session and preparing your LiRA workspace."
    >
      <div className="flex flex-col items-center justify-center rounded-3xl border border-white/8 bg-white/[0.03] px-6 py-14 text-center">
        <div className="flex h-16 w-16 items-center justify-center rounded-full border border-white/10 bg-dark-surface-2">
          <LoaderCircle className="h-7 w-7 animate-spin text-accent-blue-light" />
        </div>
        <h2 className="mt-6 text-xl font-semibold text-white">Signing you in</h2>
        <p className="mt-3 max-w-sm text-sm leading-6 text-gray-400">
          Your account has been verified. LiRA will redirect you to the dashboard as soon as your profile is ready.
        </p>
      </div>
    </AuthLayout>
  );
};

export default OAuthCallbackPage;
