// frontend/src/pages/RegisterPage.tsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AlertCircle, ArrowRight, Lock, Mail, UserRound } from 'lucide-react';
import { useAuthStore } from '../stores/authStore';
import AuthLayout from '../components/layout/AuthLayout';

const RegisterPage: React.FC = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [username, setUsername] = useState('');
  const [fullName, setFullName] = useState('');
  const [error, setError] = useState('');
  const register = useAuthStore((state) => state.register);
  const isLoading = useAuthStore((state) => state.isLoading);
  const navigate = useNavigate();

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError('');

    try {
      await register(email, password, username || undefined, fullName || undefined);
      navigate('/');
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Registration failed. Please try again.');
    }
  };

  return (
    <AuthLayout
      eyebrow="Create account"
      title="Set up your research workspace"
      description="Create a secure LiRA account to launch reviews, monitor every stage, and keep approval decisions visible to your team."
    >
      {error && (
        <div className="mb-5 flex items-start gap-3 rounded-2xl border border-accent-rose/20 bg-accent-rose/10 px-4 py-3 text-sm text-accent-rose">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-5">
        <div className="grid gap-5 sm:grid-cols-2">
          <div>
            <label htmlFor="register-fullname" className="field-label">
              Full name
            </label>
            <div className="relative">
              <UserRound className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" />
              <input
                id="register-fullname"
                type="text"
                value={fullName}
                onChange={(event) => setFullName(event.target.value)}
                className="input-dark pl-11"
                placeholder="Jane Doe"
              />
            </div>
          </div>

          <div>
            <label htmlFor="register-username" className="field-label">
              Username
            </label>
            <input
              id="register-username"
              type="text"
              value={username}
              onChange={(event) => setUsername(event.target.value)}
              className="input-dark"
              placeholder="janedoe"
            />
          </div>
        </div>

        <div>
          <label htmlFor="register-email" className="field-label">
            Email
          </label>
          <div className="relative">
            <Mail className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" />
            <input
              id="register-email"
              type="email"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
              className="input-dark pl-11"
              placeholder="you@example.com"
              required
            />
          </div>
        </div>

        <div>
          <div className="mb-2 flex items-center justify-between gap-3">
            <label htmlFor="register-password" className="field-label mb-0">
              Password
            </label>
            <span className="text-xs text-gray-500">Minimum 8 characters</span>
          </div>
          <div className="relative">
            <Lock className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" />
            <input
              id="register-password"
              type="password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              className="input-dark pl-11"
              placeholder="Create a strong password"
              minLength={8}
              required
            />
          </div>
        </div>

        <button
          id="register-submit"
          type="submit"
          disabled={isLoading}
          className="btn-primary w-full"
        >
          {isLoading ? (
            <>
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
              Creating account
            </>
          ) : (
            <>
              Create account
              <ArrowRight className="h-4 w-4" />
            </>
          )}
        </button>
      </form>

      <div className="mt-6 rounded-2xl border border-white/8 bg-white/[0.03] px-4 py-3 text-sm text-gray-400">
        Already have an account?{' '}
        <Link to="/login" className="font-semibold text-white hover:text-accent-cyan">
          Sign in
        </Link>
      </div>
    </AuthLayout>
  );
};

export default RegisterPage;

// frontend/src/pages/RegisterPage.vue
<template>
  <AuthShell
    eyebrow="Create Account"
    title="Set up your research workspace"
    description="Create a secure account to launch reviews, inspect each step, and keep your approval decisions visible."
  >
    <Message v-if="error" severity="error" class="w-full">
      {{ error }}
    </Message>

    <div class="register-grid">
      <div class="flex flex-column gap-2">
        <label for="register-full-name" class="text-sm font-semibold">Full name</label>
        <InputText
          id="register-full-name"
          v-model="fullName"
          placeholder="Jane Doe"
          autocomplete="name"
        />
      </div>

      <div class="flex flex-column gap-2">
        <label for="register-username" class="text-sm font-semibold">Username</label>
        <InputText
          id="register-username"
          v-model="username"
          placeholder="janedoe"
          autocomplete="username"
        />
      </div>
    </div>

    <div class="flex flex-column gap-4">
      <div class="flex flex-column gap-2">
        <label for="register-email" class="text-sm font-semibold">Email</label>
        <InputText
          id="register-email"
          v-model="email"
          type="email"
          placeholder="you@example.com"
          autocomplete="email"
        />
      </div>

      <div class="flex flex-column gap-2">
        <label for="register-password" class="text-sm font-semibold">Password</label>
        <Password
          id="register-password"
          v-model="password"
          input-class="w-full"
          toggle-mask
          :feedback="false"
          placeholder="Create a strong password"
          autocomplete="new-password"
        />
      </div>

      <Button
        label="Create account"
        icon="pi pi-arrow-right"
        icon-pos="right"
        :loading="authStore.isLoading"
        @click="handleSubmit"
      />
    </div>

    <p class="auth-footnote">
      Already have an account?
      <RouterLink class="auth-link ml-1" to="/login">
        Sign in
      </RouterLink>
    </p>
  </AuthShell>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Message from 'primevue/message';
import Password from 'primevue/password';

import AuthShell from '@/components/auth/AuthShell.vue';
import { getErrorMessage } from '@/lib/workflow';
import { useAuthStore } from '@/stores/auth';

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();

const email = ref('');
const password = ref('');
const username = ref('');
const fullName = ref('');
const error = ref('');

function resolveRedirect() {
  const redirect = route.query.redirect;
  return typeof redirect === 'string' && redirect.trim() ? redirect : '/';
}

async function handleSubmit() {
  if (!email.value.trim() || !password.value) {
    return;
  }

  error.value = '';

  try {
    await authStore.register(
      email.value.trim(),
      password.value,
      username.value.trim() || undefined,
      fullName.value.trim() || undefined,
    );
    await router.push(resolveRedirect());
  } catch (err) {
    error.value = getErrorMessage(err, 'Registration failed. Please try again.');
  }
}
</script>

<style scoped>
.register-grid {
  display: grid;
  gap: 1rem;
}

.auth-footnote {
  margin: 0;
  color: var(--app-text-soft);
  line-height: 1.7;
}

.auth-link {
  font-weight: 700;
}

@media (min-width: 720px) {
  .register-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}
</style>
